name: upload

on:
  workflow_call:
    inputs:
      build_name:
        required: true
        type: string
        description: The build's name
    secrets:
      conda-pytorchbot-token:
        required: true
        description: Conda PyTorchBot token
jobs:
  build:
    runs-on: ubuntu-22.04
    container:
      image: continuumio/miniconda3:4.12.0
    steps:
      - name: Checkout PyTorch
        uses: pytorch/pytorch/.github/actions/checkout-pytorch@master
        with:
          no-sudo: true

      - name: Prune binaries
        env:
          ANACONDA_API_TOKEN: ${{ secrets.conda-pytorchbot-token }}
        run: |
            set -ex
            bash ./scripts/release/anaconda-prune/run.sh
